Rails.application.routes.draw do
  
  # generated by scaffold to take care of all the methods for subjects
  resources :subjects
  # sends a get request to the show method in the sessions controller
  get '/sessions', to: 'sessions#show'
  # sends a post request to the show method in the sessions controller with a parameter passed from the view
  post '/sessions', to: 'sessions#show', as: :sessions_show
  # sends the root to the landig page
  root 'welcome#index'
end
